### ISSUE TITLE
The RoadDamageDataset_v1 not found

### ISSUE THREAD

**Issue by shu11** [sekilab/RoadDamageDetector#11]
I'm interested in the damage dataset. Your work is excellent and I want to study it. But the dataset is currently not found (Access Denied response is returned from AWS S3).

Could you please share your dataset again?

**Comment by hiroyamaeda** [comment]
I changed the link . The link was expired. Please try again! Thank you for your interest!

**Comment by shu11** [comment]
Thanks a lot!

**Comment by jannz10** [comment]
please help me i connt find the dataset.and do you have a yolov3 of dis?thanks alot

**Comment by jannz10** [comment]
i try to check the dataset its access denied also

**Comment by hiroyamaeda** [comment]
Please check now!
