### ISSUE TITLE
Unable to download trained models (70MB)

### ISSUE THREAD

**Issue by rxl204** [sekilab/RoadDamageDetector#14]
broken link

**Comment by Jooliee** [comment]
same!!

**Comment by thakurpranav5** [comment]
please add a valid link

**Comment by thakurpranav5** [comment]
so that we can dowload trained model

**Comment by thakurpranav5** [comment]
Hi Hiroyamaeda I am not able to download trained dataset the link is showing error, access denied please help me @hiroyamaeda

**Comment by thakurpranav5** [comment]
Hi Hiroya Maeda I am not able to download trained dataset the link is showing error, access denied please help me @hiroyamaeda

**Comment by thakurpranav5** [comment]
Hi can you you please help to provide a valid link for trained models (75mb) @ksym27 @tosseto @homata @rxl204 @Jooliee @hiroyamaeda

**Comment by ALTAIR-VEGA** [comment]
Same thing, we would really appreciate it

**Comment by elvinest** [comment]
Same, please update download url, thx!

**Comment by hiroyamaeda** [comment]
Sorry for the late response. We've fixed the link.
