### ISSUE TITLE
When loading the dataset, I'm getting a unicodeDecodeError

### ISSUE THREAD

**Issue by adityabharadwaj198** [sekilab/RoadDamageDetector#8]
Traceback (most recent call last):
  File "roaddamagedataset.py", line 30, in <module>
    tree = ElementTree.parse(infile_xml)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 45: invalid start byte

this is what the traceback for the error is. Thank you

**Comment by bygreencn** [comment]
@adityabharadwaj198 maybe it caused by the hidden files in all Annotations folders.

**Comment by tanajikamble13** [comment]
thnks @adityabharadwaj198

**Comment by RedmondMax** [comment]
annotation XML files seems cp1252 encode ?  XML parse does not work for me. 

   Mac OS X                   2   ~      °                                      ATTR       °   ˜                     ˜     com.apple.quarantine q/0081;5a5bf4e8;Safari;

**Comment by RedmondMax** [comment]
/anaconda/envs/py36/lib/python3.6/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 45: invalid start byte

**Comment by hiroyamaeda** [comment]
Thanks! @bygreencn
